---
- name: Check if npm is installed
  command: npm -v
  register: npm_check

- name: install npm
  apt:
    name: npm
    update_cache: yes
  when: npm_check.rc == 1

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Build app
  shell: apt install nodejs -y