---
- name: Remove base directory (if present)
  file:
    path: '{{ base_dir }}'
    state: absent
  when: rebuild_db|bool

- name: Clone Git repository
  git:
    repo: '{{ git_repo }}'
    dest: '{{ appdata_dir }}'
    version: '{{ git_branch }}'
  when: rebuild_db|bool

- name: Add directory to the safe config
  git_config:
    name: safe.directory
    value: '{{ appdata_dir }}'
    scope: global

- name: Update Git repository
  git:
    repo: '{{ git_repo }}'
    dest: '{{ appdata_dir }}'
    version: '{{ git_branch }}'
    clone: no
    update: yes
    force: yes

- name: Create virtual environment dir
  file:
    path: "'{{ base_dir }}'/.venvs"
    state: directory

- name: Create a virtual environment
  command: "{{ virtualenv_cmd }} '{{ base_dir }}'/.venvs"
  when: rebuild_db|bool
  environment:
    PYTHONPATH: "'{{ base_dir }}'"

- name: Install requirements.txt
  pip:
    requirements: '{{ appdata_dir }}/requirements.txt'
    virtualenv: "{{ base_dir }}/.venvs/{{ app_name }}"

- name: Set permissions for base directory
  file:
    path: '{{ base_dir }}'
    owner: '{{ uid }}'
    group: '{{ gid }}'
    state: directory
    recurse: yes

- name: Configure/modify app
  lineinfile:
    path: '{{ appdata_dir }}/{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items: '{{ line_changes }}'
