---
- name: Add deadsnakes repo for Python 3.11
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
    state: present
    update_cache: yes

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 1 #One day

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
