---
- name: Add deadsnakes repo for Python 3.11
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
    state: present
    update_cache: yes

- name: remove nodejs
  apt:
    name: nodejs
    state: absent
    purge: true

- name: clear out any previous nodejs nonsense
  shell: dpkg -r --force-remove-reinstreq libnode-dev

- name: clear out any previous nodejs nonsense
  shell: dpkg -r --force-remove-reinstreq libnode72:amd64

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
