- name: Create droplet
  hosts: digitalocean
  roles:
    - setup_droplet

- name: Configure droplet for Custom Stream Overlay
  hosts: custom-stream-overlay
  remote_user: root
  become: yes

  vars:
    app_name: 'custom-stream-overlay'
    nginx_http_port: 80
    line_changes:
      - path: 'src/js/Settings.js'
        regexp: "^\\s*API_HOST: 'http://127.0.0.1',"
        line: "API_HOST: '{{ inventory_hostname }}',"
    nginx_server_name: localhost

  roles:
    - install_react_app_deps
    - setup_react_app
    - patch_config_Debian_Ubuntu
    - configure_nginx
    - start_nginx
    - setup-ssl
    - start_nginx

- name: Configure droplet for Custom Stream API
  hosts: custom-stream-overlay
  remote_user: root
  become: yes

  vars:
    app_name: 'custom-stream-api'
    app_package: "custom_stream_api.server"
    app_callable: "app"
    nginx_http_port: 5000
    nginx_http_location: null
    uwsgi_sockets: true
    uwsgi_threads: 5
    line_changes:
      - path: 'custom_stream_api/settings.py'
        regexp: "^\\s*SECRET = ''"
        line: "SECRET = '{{ secret_key }}'"

  roles:
    - install_web_app_packages
    - setup_venv_app
    - setup_flask_db
    - patch_config_Debian_Ubuntu
    - configure_nginx
    - configure_uwsgi
    - create_service_Debian_Ubuntu
    - start_uwsgi
    - start_nginx
    - setup-ssl
    - start_nginx

- name: Configure droplet for Custom Stream Dashboard
  hosts: custom-stream-overlay
  remote_user: root
  become: yes

  vars:
    app_name: 'custom-stream-dashboard'
    nginx_http_port: 8080
    line_changes:
      - path: 'src/js/Settings.js'
        regexp: "^\\s*API_HOST: 'http://127.0.0.1',"
        line: "API_HOST: 'http://{{ inventory_hostname }}',"
    nginx_server_name: localhost

  roles:
    - install_react_app_deps
    - setup_react_app
    - configure_nginx
    - patch_config_Debian_Ubuntu
    - start_nginx
    - setup-ssl
    - start_nginx
