- name: Create droplet
  hosts: digitalocean
  roles:
    - setup_droplet

- name: Configure droplet for Custom Stream API
  hosts: custom-stream-overlay
  remote_user: root
  become: yes

  vars:
    app_name: 'custom-stream-api'
    app_package: "custom_stream_api.server"
    app_callable: "app"
    nginx_http_port: 5000

  roles:
    - install_Debian_Ubuntu
    - setup_venv_app
    - patch_config_Debian_Ubuntu
    - configure_nginx_uwsgi
    - create_service_Debian_Ubuntu
    - start_services

- name: Configure droplet for Custom Stream Overlay
  hosts: custom-stream-overlay
  remote_user: root
  become: yes

  vars:
    app_name: 'custom-stream-overlay'

  roles:
    - install_npm_nodejs
    - setup_react_app
    - configure_nginx_uwsgi
    - start_services