- import_playbook: setup_droplet.yml
- name: Configure droplet for Custum Stream Dashboard
  hosts: custom-stream-overlay
  remote_user: root
  become_method: sudo

  vars:
    secret_key: "{{ lookup('env', 'SECRET_KEY') }}"

  tasks:

    - name: make git directory
      file:
        path: /git
        state: directory
        mode: 0755

    # CUSTOM STREAM API
    - name: install pip3
      apt:
        name: python3-pip
        update_cache: yes

    - name: make clone directory
      file:
        path: /git/custom-stream-api
        state: directory

    - name: git custom stream API
      git:
        repo: "https://github.com/b0ses/custom-stream-api.git"
        dest: /git/custom-stream-api

    - name: install custom stream API's dependencies
      pip:
        requirements: /git/custom-stream-api/requirements.txt

    - name: populate secret key
      lineinfile:
          path: /git/custom-stream-api/settings.py
          regexp: "^SECRET = ''"
          line: "SELINUX = '{{ secret_key }}'"
