- name: setup DO droplet
  hosts: digitalocean

  vars:
    do_token: "{{ lookup('env', 'DO_API_KEY') }}"
    droplet_name: "{{ lookup('env', 'project') }}"

  tasks:

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/id_rsa

  - debug: msg="Do_token {{ do_token }}"
  - debug: msg="User {{ ansible_user_id }}"

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=jenkins-key
      ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
      api_token={{ do_token }}
    register: jenkins_key

  - name: ensure droplet exists
    digital_ocean: >
      state=present
      command=droplet
      name={{ droplet_name }}
      unique_name=yes
      size_id=1gb
      region_id=nyc1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ jenkins_key.ssh_key.id }}
      api_token={{ do_token }}
    register: current_droplet

  - debug: msg="IP is {{ current_droplet.droplet.ip_address }}"

  - name: Add new droplet to host group
    local_action: add_host hostname={{ current_droplet.droplet.ip_address }} groupname={{ droplet_name }}

  - name: Wait for SSH to come up
    local_action: wait_for host={{ current_droplet.droplet.ip_address }} port=22 timeout=320 state=started
