---
- name: Install packages (Debian/Ubuntu)
  apt:
    name: nginx-full,git
    state: present
    update_cache: yes

- name: Check if npm is installed
  command: npm -v
  register: npm_check
  ignore_errors: yes

- name: Install npm
  apt:
    name: npm
    update_cache: yes
  when: npm_check|bool == False
  ignore_errors: yes

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  when: npm_check|bool == False

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: npm_check|bool == False

- name: Update nodejs
  shell: apt install nodejs -y
  when: npm_check|bool == False

- name: Prevent it from being upgraded
  ansible.builtin.dpkg_selections:
  name: nodejs
  selection: hold
