---
- name: ensure ssh key exists
  user: >
    name={{ ansible_user_id }}
    generate_ssh_key=yes
    ssh_key_file=.ssh/id_rsa

- name: Set authorized key took from file
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    exclusive: True

- name: Ensure key exists at DigitalOcean
  digital_ocean_sshkey: >
    state=present
    name=jenkins-key
    ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
    oauth_token={{ do_token }}
  register: jenkins_key

- name: Ensure droplet exists
  digital_ocean_droplet: >
    state=present
    name={{ app_name }}
    unique_name=yes
    size=1gb
    region=nyc1
    image=ubuntu-18-04-x64
    ssh_keys=[{{ jenkins_key.data.ssh_key.id }}]
    oauth_token={{ do_token }}
  register: current_droplet

- debug: msg="IP is {{ current_droplet.data.ip_address }}"

- name: Wait for SSH to come up
  local_action: wait_for host={{ current_droplet.data.ip_address }} port=22 timeout=320 state=started

- name: Adding domain for droplet
  digital_ocean_domain:
    state: present
    name: "{{ domain_name }}"
    ip: "{{ current_droplet.data.ip_address }}"

- name: Add new droplet to host group
  local_action: add_host hostname={{ current_droplet.data.ip_address }} groupname={{ app_name }}

- name: Wait for domain to come up
  local_action: wait_for host={{ domain_name }} port=22 timeout=320 state=started