---

- name: Add admin key to .ssh/id_rsa.pub
  shell: |
    mkdir -p ~/.ssh
    echo "${{ admin_pub_key }}" > ~/.ssh/id_rsa.pub
    chmod 644 ~/.ssh/id_rsa.pub

- name: Set authorized key took from file
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    exclusive: True

- name: Ensure key exists at DigitalOcean
  digitalocean.cloud.ssh_key:
    state: present
    name: admin-key
    public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    oauth_token: "{{ do_token }}"
  register: admin_key

- name: Ensure droplet exists
  digitalocean.cloud.droplet:
    state: present
    name: "{{ app_name }}"
    unique_name: yes
    size: 1gb
    region: nyc1
    image: ubuntu-22-04-x64
    ssh_keys:
      - admin_key.data.ssh_key.id
    oauth_token: "{{ do_token }}"
  register: current_droplet

- name: Print IP 2
  ansible.builtin.debug:
    msg: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Print IP
  ansible.builtin.debug:
    msg: "IP is {{ current_droplet.droplet.networks.v4[0].ip_address }}"

- name: Wait for SSH to come up
  local_action: wait_for host={{ current_droplet.droplet.networks.v4[0].ip_address }} port=22 timeout=320 state=started

- name: Adding domain for droplet
  digitalocean.cloud.domain:
    state: present
    name: "{{ domain_name }}"
    ip_address: "{{ current_droplet.droplet.networks.v4[0].ip_address }}"

- name: Add new droplet to host group
  local_action: add_host hostname={{ current_droplet.droplet.networks.v4[0].ip_address }} groupname={{ app_name }}

- name: Wait for domain to come up
  local_action: wait_for host={{ domain_name }} port=22 timeout=320 state=started
