- name: Upgrade/rebuild database
  shell:
    cmd: "'{{ base_dir }}/bin/flask' db upgrade head -d migrations"
    chdir: '{{ module_dir }}'
  environment:
    FLASK_APP: server.py

- name: Set permissions for db directory
  file:
    path: '{{ module_dir }}'
    mode: 777
    state: directory
    recurse: yes

- name: Moving back appdata_dir
  command: 'chdir={{ appdata_dir }}'
