- name: Upgrade/rebuild database
  shell:
    cmd: "'{{ base_dir }}/bin/flask' db upgrade head -d {{ module_dir }}/migrations"
    chdir: '{{ module_dir }}'
  environment:
    FLASK_APP: server.py

- name: Set permissions for database
  file:
    path: '{{ module_dir }}/app.db'
    mode: 770
