- shell: pwd
  register: current_cwd

- name: Upgrade/rebuild database
  shell:
    cmd: "'{{ base_dir }}/bin/flask' db upgrade head -d migrations"
    chdir: '{{ module_dir }}'
  environment:
    FLASK_APP: server.py

- name: Set permissions for db directory
  file:
    path: '{{ module_dir }}'
    mode: 777
    state: directory
    recurse: yes

- shell:
    cmd: 'chdir={{ current_cwd }}'
