- name: Upgrade/rebuild database
  shell:
    cmd: "alembic upgrade head"
    chdir: '{{ module_dir }}'
  environment:
    PYTHONPATH: "'{{ base_dir }}'"

- name: Set permissions for db directory
  file:
    path: '{{ base_dir }}'
    owner: '{{ uid }}'
    group: '{{ gid }}'
    state: directory
    recurse: yes
