---
- name: Check if nginx is running
  command: systemctl status nginx
  ignore_errors: yes
  changed_when: false
  register: service_status

- name: Stop nginx service (if running)
  systemd:
    name: nginx
    state: stopped
  when: service_status


- name: Clear out all nginx configs (if they exist)
  shell: /bin/rm -rf {{ nginx_dir }}/*
  when: service_status
