---
- name: Install packages (Debian/Ubuntu)
  apt:
    name: python3.11,python3-pip,python3.11-distutils,libpq-dev,uwsgi,uwsgi-emperor,uwsgi-plugin-python3,python3.11-dev,nginx-full,git
    state: present
    update_cache: yes

- name: python3-venv is special
  apt:
    name: python3.11-venv
    state: present
    update_cache: yes

- name: Update pip3
  pip:
    name: pip
    state: latest
