---
- name: Install packages (Debian/Ubuntu)
  apt:
    name: python3,python3-pip,python3-distutils,uwsgi,uwsgi-emperor,uwsgi-plugin-python3,python3-dev,nginx-full,git
    state: present
    update_cache: yes

- name: python3-venv is special
  apt:
    name: python3-venv
    state: present
    update_cache: yes
