---
- name: Add ppa:deadsnakes/ppa repo
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
    state: present
    update_cache: yes

- name: Install packages (Debian/Ubuntu)
  apt:
    name: python3.7,uwsgi,uwsgi-emperor,uwsgi-plugin-python3,python3-dev,nginx-full,git
    state: present
    update_cache: yes

- name: python3-venv is special
  apt:
    name: python3-venv
    state: present
    update_cache: yes
