---
- name: Remove base directory (if present)
  file:
    path: '{{ base_dir }}'
    state: absent

- name: Clone Git Repository
  git:
    repo: '{{ git_repo }}'
    dest: '{{ base_dir }}'
    version: '{{ git_branch }}'

- name: Install packages based on package.json
  npm:
    path: '{{ base_dir }}'

- name: Configure/modify app
  lineinfile:
    path: '{{ base_dir }}/{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items: '{{ line_changes }}'

- name: Build app
  shell:
    cmd: npm run build
    chdir: '{{ base_dir }}'
