chdir = "{{ appdata_dir }}"
worker_class = "uvicorn_worker.UvicornWorker"
workers = {{ gunicorn_processes }}
accesslog = "{{ base_dir }}/gunicorn.log"
errorlog = "{{ base_dir }}/gunicorn.log"
user = "{{ uid }}"
group = "{{ gid }}"
umask = "775"
# mode = "775"
capture_output = True
